### ISSUE TITLE
DiskLruCache#STRING_KEY_PATTERN does not allow capital letters in cache keys

### ISSUE THREAD

**Issue by davivel** [JakeWharton/DiskLruCache#73]
Is there any reason for this constraint?

Thanks.

**Comment by necronet** [comment]
Should the DiskLruCache#validateKey method be public to be able to override it?

**Comment by JakeWharton** [comment]
The class is `final`.

**Comment by necronet** [comment]
So I supposed @davivel davivel would have to do a downcase to its keys,

**Comment by swankjesse** [comment]
Case insensitive file systems are everywhere, including Android. You're better off hashing your file name when creating a cache key.

**Comment by davivel** [comment]
We already solved it, thanks.
