### ISSUE TITLE
DiskLruCache and MediaPlayer

### ISSUE THREAD

**Issue by vdurmont** [JakeWharton/DiskLruCache#78]
Hi,

I'd like to use DiskLruCache to store media files that I would play in a [MediaPlayer](http://developer.android.com/reference/android/media/MediaPlayer.html) later.
My problem is that the possible inputs to set the data source of a `MediaPlayer` are:
* An `Uri`
* A `FileDescriptor`
* A path

The `DiskLruCache.Snapshot` only returns an `InputStream` so the only solution for me is to write the stream to a temp `File` and create a new `FileInputStream`. That's not really something I want to do :smile: 
After a quick look under the hood, I saw that you are actually using `FileInputStream` so I suppose I could just cast the stream but it seems like a bad solution since the API doesn't specify it ==> it could break at any moment.

If we add a `getFileInputStream` or a `getUri` method to the `DiskLruCacheSnapshot` class, would it be a bad thing? I prefer to discuss this with you before working on a pull request.

Thanks for your help!

**Comment by swankjesse** [comment]
I don't think we want to add `File` here, particularly because the underlying files aren't stable. Anything that receives a `File` is naturally racy because of eviction.

You'll have to fork `DiskLruProject` to add this API!

**Comment by vdurmont** [comment]
Ok thanks for your answer, that's what I was afraid of :wink: 
Will fork then!
