### ISSUE TITLE
Does getCacheDir() supported?

### ISSUE THREAD

**Issue by virl** [JakeWharton/DiskLruCache#79]
Does this library supports working in context.getCacheDir()?

**Comment by JakeWharton** [comment]
Yes. Any folder that can be written to will work.

**Comment by virl** [comment]
What happens if user or Android deletes that folder when it is accessed by running app that uses this library?
Will get() return null or some exception will be thrown? What if journal file becomes missing in the middle of put()?

**Comment by JakeWharton** [comment]
It will return null and the write will fail silently. See the tests for
examples of this.
