### ISSUE TITLE
Simplify interface and make lib truly asynchronous

### ISSUE THREAD

**Issue by virl** [JakeWharton/DiskLruCache#80]
I propose to radically simplify interface of DiskLruCache class to the likes of TMCache (https://github.com/tumblr/TMCache):

1. Simple get/put methods that block (and do not throw) if another thread makes modification to the cache.

2. No editor() method that throws pesky exceptions.

3. Ability to put and get values from/to the cache asynchronously by supplying callbacks that will be called on background thread with results (cache must maintain or receive thread pool via ExecutorService). This will allow to use the cache to get complex images from the disk and generate thumbnails for them in background threads.

4. Complex Entries with indexes inside the cache are NOT needed because they complicate cache logic — simple key/value storage is enough.

5. Make the cache to use getCacheDir() directory by default.

Proposed interface:
```
public interface Cache<Key, Value>
{
	interface GetResult<Key, Value>
	{
		void cacheDidGetObject(Cache cache, Key key, Value object);
	}

	interface PutResult<Key, Value>
	{
		void cacheDidPutObject(Cache cache, Key key, Value object);
	}

	Value get(Key key); // Blocks until value is retrieved.
	void get(Key key, Cache.GetResult<Key, Value> callback);

	void put(Key key, Value value); // Blocks if another thread puts value with same key.
	void put(Key key, Value value, Cache.PutResult<Key, Value> callback);
} // Cache
```

**Comment by JakeWharton** [comment]
Synchronous pushes threading model to the caller who's often on a BG thread already (e.g., making an HTTP call). Complex entries are needed as your parameterized API offers no explanation of how complex key value types are serialized. And finally, this is not an Android library so it cannot know about getCacheDir().

Either write a high-level wrapper or use another library. These changes will not be made.

**Comment by virl** [comment]
Ok, getCacheDir() is not needed.

But complex entries is not needed - just allow caller to supply serializer to/from byte[].

This is not android library, but most usages for such cache is on the android, because servers use Redis/Memcache and other distributed services for caching and your solution is not scalable.

**Comment by JakeWharton** [comment]
I shipped something similar in a different library and it was a terrible
decision for something at this level. I will not be adding it here so you
are welcome to try your ideas in a fork or a separate library.

**Comment by virl** [comment]
Thanks, I'm already thinking about making my small library for android disk cache. Maybe if it will be finished, I will post it to github.

Btw, look at your forks: most of them are fixes for Android. There is even separate wrapper library called Reservoir (but unusable due to poor design).
