### ISSUE TITLE
Closing the correct resource ?

### ISSUE THREAD

**Issue by jeremydubreil** [JakeWharton/DiskLruCache#83]
Hi,

Is this line closing the correct resource https://github.com/JakeWharton/DiskLruCache/blob/master/src/main/java/com/jakewharton/disklrucache/Util.java#L44 ?

I would expect:

  `writer.close()`

instead of:

  `reader.close()`

**Comment by JakeWharton** [comment]
`StringWriter` does not need closed as it holds no actual resource. The method is for exhausting the `reader` variable so closing it in the `finally` block is the correct thing to do.
