### ISSUE TITLE
Old Image is always shown

### ISSUE THREAD

**Issue by nicolasmingo** [JakeWharton/DiskLruCache#87]
When an image changes from the server, DiskLruCache will always load the old image saved in the file system.

**Scenario**
1. Load an image URL provided by the server (the image is saved to DiskLruCache)
2. Reload the same URL (the image is loaded now from DiskLruCache)
2. Change the image from server
3.  reload the image URL (the image is also loaded from DiskLruCache but the image has changed in the server)

**Actual Results**
the old image is shown

**Expected results**
the new image should be shown

**Additional information**
Cache-Control and Expiration HTTP headers are correct to let volley reloading image from the server.
(I think DiskLruCache is not designed for this need)

**Comment by swankjesse** [comment]
How are you using DiskLruCache? On its own it knows nothing about HTTP, your server, or cache-control headers.
