### ISSUE TITLE
Basic usage and code samples?

### ISSUE THREAD

**Issue by ghost** [JakeWharton/DiskLruCache#90]
Wouldn't it be a good idea to provide some basic usage instructions and code samples?

**Comment by JakeWharton** [comment]
The API is fairly trivial and can be browsed at http://jakewharton.github.io/DiskLruCache. The README also contains a description of how to use the API. And finally, there's tons of tests that show how it can be used: https://github.com/JakeWharton/DiskLruCache/blob/master/src/test/java/com/jakewharton/disklrucache/DiskLruCacheTest.java

We're currently working on DiskLruCache2 in OkHttp so I don't really want to invest a lot of time here when the whole API is about to be replaced.
