### ISSUE TITLE
while loop in StrictLineReader.java

### ISSUE THREAD

**Issue by TinyAndNeo** [JakeWharton/DiskLruCache#97]
`      while (true) {
        out.write(buf, pos, end - pos);
        // Mark unterminated line in case fillBuf throws EOFException or IOException.
        end = -1;
        fillBuf();
        // Try to find LF in the buffered data and return the line if successful.
        for (int i = pos; i != end; ++i) {
          if (buf[i] == LF) {
            if (i != pos) {
              out.write(buf, pos, i - pos);
            }
            pos = i + 1;
            return out.toString();
          }
        }
      }`
I dont understand the `while` means what,If `in` is not changed in `fillBuf()`,it will be an endless loop, 
I find it when I try to translate the java file to kt file for kotlin

**Comment by ncruces** [comment]
If you can't find a newline, you will eventually reach the end of stream, and throw [here](https://github.com/JakeWharton/DiskLruCache/blob/5b45d10/src/main/java/com/jakewharton/disklrucache/StrictLineReader.java#L190).

**Comment by TinyAndNeo** [comment]
thx
